// Default search suggestions to give the user more to choose from than just 
const SearchSuggestions =  [
  "Entertainment",
  "Electronics",
  "TVs",
  "Computers",
  "Cellphones",
  "Video Games",
  "Movies & TV",
  "Books",
  "Personal Care",
  "Clothing & Jewelry",
  "Movies",
  "Television",
  "Games",
  "Toys",
  "Hardware",
  "Tools",
  "Playstation",
  "Playstation 5",
  "Playstation 4",
  "Playstation 3",
  "Playstation 2",
  "Playstation 1",
  "Playstation",
  "Xbox",
  "Xbox 360",
  "Xbox One",
  "Xbox Series X",
  "Nintendo",
  "Wii",
  "Nindento Switch",
  "Contollers",
  "Clothes",
  "Jewelry",
  "Shirts",
  "Shoes",
  "Pants",
  "Shorts",
  "Dress Shirts",
  "I-Shirts",
  "T Shirts",
  "Polos",
  "Boots",
  "Colar Shirts",
  "Dresses",
  "Hats",
  "Gowns",
  "Glasses",
  "Sun Glasses",
  "Auto",
  "Automobile",
  "Automobile Parts",
  "Screw Drivers",
  "Screws",
  "Wrenches",
  "Hammers",
  "Saws",
  "Pliers",
  "Camping Gear",
  "Tents",
  "Axes",
  "Desktop Computers",
  "Hard Drives",
  "Thumb Drives",
  "Flash Drives",
  "Mouses",
  "Keyboards",
  "Key Bords",
  "Pets",
  "Pet Foot",
  "Cat Toys",
  "Dog Toys",
  "Cat Food",
  "Dog Food",
  "4K TV",
  "4K Television",
  "Blue Ray Player",
  "HD TV",
  "HD Television",
  "4k Monitor",
  "4k Computer Screen",
  "HD Monitoe",
  "HD TV",
  "High Definition",
  "Remotes",
  "Samsung",
  "Roku",
  "Apple",
  "Microsoft",
  "iPhone",
  "Galaxy",
  "Google Pixel",
  "LG",
  "Smartphones",
  "Sprint",
  "Verison",
  "AT&T"
]

export default SearchSuggestions;